# This file is used to define the services that will be used in the application.
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    image: kumaranayakages/homehunt-server-image:v8
    container_name: server_container
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO=mongodb+srv://Sachinthana:Sachi2001@cluster0.ge4oi.mongodb.net/homehunt?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=mysecretkey123

  client:
    image: kumaranayakages/homehunt-client-image:v7
    container_name: client_container
    restart: always
    depends_on:
      - server
    stdin_open: true
    tty: true
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"

volumes:
  mongo_data:
